### ISSUE TITLE
Regression: changing log-level does not work anymore

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-cli#1063] opened 2019-07-04 10:04 UTC
`hlx build --log-level=silly`
`hlx publish --log-level=silly`

Those commands should output a lot of logs. But output does not change compare to not using the option: it is not taken into account.

**Comment by tripodsan** [comment] 2019-07-05 07:29
basically works as expected:

I added this:

```diff
diff --git a/src/build.cmd.js b/src/build.cmd.js
index 597b4e9..11cdd18 100644
--- a/src/build.cmd.js
+++ b/src/build.cmd.js
@@ -82,6 +82,11 @@ class BuildCommand extends AbstractCommand {
   }

   async build() {
+    this.log.silly('silly');
+    this.log.debug('debug');
+    this.log.info('info');
+    this.log.warn('warn');
+    this.log.error('error');
     this.emit('buildStart');
     // expand patterns from command line arguments
     const myfiles = this._files.reduce((a, f) => [...a, ...glob.sync(f)], []);
```

and now:

```
$ hlx build --log-level=silly
silly: silly
debug: debug
info
warn: warn
error: error
```

**Comment by tripodsan** [comment] 2019-07-05 07:30
```
$ hlx package --log-level=silly
(node:6131) ExperimentalWarning: The fs.promises API is experimental
[========================================----------]  4.6sdebug: preparing package html.zip
debug: preparing package json.zip
debug: preparing package xml.zip
debug: html.zip: A package.json
debug: json.zip: A package.json
debug: xml.zip: A package.json
debug: json.zip: A json.js
[===============================================---] packaging json.js 4.8sdebug: json.zip: Created package. 2170127 total bytes
debug: xml.zip: A xml.js
debug: xml.zip: Created package. 2237183 total bytes
debug: html.zip: A html.js
[==================================================] packaging html.js 4.9s
debug: html.zip: Created package. 3624511 total bytes
✅  packaging completed
```

**Comment by tripodsan** [comment] 2019-07-05 07:33
the problem is rather, that there are no silly logs:

```
$ fgrep -R log.silly src

$ fgrep -R log.debug src
src/auth-login-server.js:        this.log.debug(req.headers);
src/auth-login-server.js:        this.log.debug(req.method);
src/auth-login-server.js:          this.log.debug('got body', body);
src/auth-login-server.js:        this.log.debug(`server started on ${JSON.stringify(this._srv.address())}`);
src/remotepublish.cmd.js:      this.log.debug('filtering');
src/remotepublish.cmd.js:        this.log.debug(`this: ${Array.from(this.config.strains.keys()).join(', ')}`);
src/remotepublish.cmd.js:        this.log.debug(`other: ${Array.from(other.strains.keys()).join(', ')}`);
src/remotepublish.cmd.js:        this.log.debug(Array.from(merged.strains.keys()).join(', '));
src/remotepublish.cmd.js:        this.log.debug(`ignoring proxy strain ${strain.name}`);
src/remotepublish.cmd.js:        this.log.debug(`ignoring unaffected strain ${strain.name}`);
src/package.cmd.js:      log.debug(`preparing package ${archiveName}`);
src/package.cmd.js:          log.debug(`${archiveName}: Created package. ${archive.pointer()} total bytes`);
src/package.cmd.js:        log.debug(`${archiveName}: A ${data.name}`);
```

**Comment by tripodsan** [comment] 2019-07-05 07:35
closing as `works for me`.

**Closed by tripodsan** 2019-07-05 07:35 UTC
Labels: bug

**Comment by kptdobe** [comment] 2019-07-05 07:38
oh... you mean we removed all debugging info! We used to have a lot of logs, especially when running `hlx publish`. 
It would be useful to be able to see what happens being the scene, like the requests made by deploy / publish... 
Thanks for checking, I'll create a follow up ticket.
