### ISSUE TITLE
support for local changes of head.html

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-cli#1883] opened 2021-11-04 15:40 UTC
as head.html is one of the first things that someone changes locally, it would be great if there was support to make changes without committing and seeing the results. i am thinking of a solution that replaces the `<head>` ... `</head>` in the body of an extensionless response with what's locally on disk in `head.html` as part of the reverse proxy process.

**Comment by tripodsan** [comment] 2021-11-04 16:54
duplicate of #1867

**Closed by tripodsan** 2021-11-04 16:54 UTC
Labels: bug
