### ISSUE TITLE
hlx up is failing for https://github.com/AdobeDocs/adobeio-codelabs-template

### ISSUE THREAD

**Issue by icaraps** [adobe/helix-cli#1356] opened 2020-04-01 13:30 UTC
**Description**
Using `hlx up` on the repository https://github.com/AdobeDocs/adobeio-codelabs-template is throwing following error and fails:
```
warn: Multiple versions of adobe/helix-log in the same process! Using one loaded first! { used: { version: '4.5.1', filename: '/Users/ringel/npm/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-log/src/index.js' }, discarded: { version: '4.5.1', filename: '/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/helix-pipeline/node_modules/@adobe/helix-log/src/index.js' } }
warn: Multiple versions of adobe/helix-log in the same process! Using one loaded first! { used: { version: '4.5.1', filename: '/Users/ringel/npm/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-log/src/index.js' }, discarded: { version: '4.5.0', filename: '/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/helix-log/src/index.js' } }
warn: Multiple versions of adobe/helix-log in the same process! Using one loaded first! { used: { version: '4.5.1', filename: '/Users/ringel/npm/lib/node_modules/@adobe/helix-cli/node_modules/@adobe/helix-log/src/index.js' }, discarded: { version: '4.5.1', filename: '/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/openwhisk-action-logger/node_modules/@adobe/helix-log/src/index.js' } }
[hlx] error: error rendering dynamic script:  { Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/utils/mdast-to-vdom.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
[hlx] error: error rendering dynamic script:  { Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/utils/mdast-to-vdom.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
[hlx] error: error rendering dynamic script:  { Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ringel/IdeaProjects/IO/adobeio-codelabs-template/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/utils/mdast-to-vdom.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
``` 

**To Reproduce**
`git clone https://github.com/AdobeDocs/adobeio-codelabs-template && cd adobeio-codelabs-template && hlx up`

**Expected behavior**
Should launch local dev env

**Version:**
8.1.10

**Comment by rofe** [comment] 2020-04-01 14:48
I was able to reproduce the error. Looks like `helix-pipeline` dependencies are not getting installed. As a workaround, you can execute
```sh
cd .hlx/pages/master/node_modules/@adobe/helix-pipeline && npm i && cd - && hlx up
```
in the project directory. This will properly install the pipeline dependencies and allow the site to be rendered.

Note: the warnings about multiple versions of `helix-log` being in the same process are unrelated.

**Comment by icaraps** [comment] 2020-04-01 15:06
@rofe thanks for the workaround ! Very helpful.

**Comment by tripodsan** [comment] 2020-04-02 03:05
@icaraps what is your npm version?

**Comment by tripodsan** [comment] 2020-04-02 03:06
> Note: the warnings about multiple versions of `helix-log` being in the same process are unrelated.

we should do something against it....

**Comment by duynguyen** [comment] 2020-04-02 09:32
I got the same issue as well, and the workaround by @rofe works 👍 
My npm version `6.13.4`.

**Comment by icaraps** [comment] 2020-04-02 09:42
I just upgraded to npm `6.14.4` and tried `hlx up` again and it's working fine now.

**Comment by rofe** [comment] 2020-04-03 07:28
Mine was `6.9.0` 🙀

**Comment by tripodsan** [comment] 2021-09-23 11:37
won't fix for helix 2. irrelevant for helix 3.

**Closed by tripodsan** 2021-09-23 11:37 UTC
Labels: bug
