### ISSUE TITLE
Problem with package build on windows

### ISSUE THREAD

**Issue by wielmic** [adobe/helix-cli#884] opened 2019-05-14 11:23 UTC
I am trying to setup helix with the runtime and fastly but it doesn't build properly. There are no errors in logs. There is only one zip package created static.zip, html.zip is missing.
I tried to build it on Windows 10 with:
node: 10.15.0
npm: 6.4.1
helix:  2.1.6 and o.14.12

Here are the steps:
1. Create empty repo on github
2. helix demo helix-demo
3. git remote add origin
4. git push origin master
5. hlx deploy with  --adddefault
6. hlx publish

It looks like it is deployed correctly to fastly, running wsk list returns following actions deployed:
hlx--static (only one)

When i invoke an action i get following error:
` "error": "Initialization has failed due to: Error: Cannot find module 'request-promise-native'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/nodejsAction/XXMIjDJm/static.js:13:17)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"`

logs are empty.

Is it a known issue?

**Comment by tripodsan** [comment] 2019-05-14 12:11
@wielmic can you try again with helix 2.5.2 ?

**Comment by wielmic** [comment] 2019-05-14 12:15
Sure, let me check.

**Comment by wielmic** [comment] 2019-05-14 12:26
There is same issue, here is the output:

[==================================================] analyzing static.js 0.0s
[==------------------------------------------------] packaging static.js 73.8s✅  packaging completed
[==================================================]  0.0s

✅  deployment of 1 actions completed:
   - pid80102/hlx--static (1.81 MiB)
Affected strains of ssh://git@github.com/wielmic/hlx-test.git#master:
- default
Updated helix-config.yaml

Only static.zip is created

**Comment by wielmic** [comment] 2019-05-14 12:28
I found another issue here, maybe this is the cause. When  run hlx build i get this error:
`
×  C:\Users\wieli\work\adobe\hlx_training\helix-demo\helix-test\src\html.pre.js: Cannot read property 'devDependencies' of undefined
    at AdapterJSAsset.getPackage (C:\Users\wieli\AppData\Roaming\npm\node_modules\@adobe\helix-cli\src\parcel\AdapterJSAsset.js:43:9)
Cannot read property 'devDependencies' of undefined`

**Comment by stefan-guggisberg** [comment] 2019-05-14 12:39
@wielmic YHEs, that's probably the root cause. see https://github.com/adobe/helix-cli/issues/881

**Comment by trieloff** [comment] 2019-05-14 12:54
Once #882 has been merged and released, please try again.

**Comment by wielmic** [comment] 2019-05-14 13:18
Looks better now, there is html.zip and i have new action deployed to the runtime:
/pid80102/github-com--wielmic--hlx-test--master-dirty/html             private nodejs:10

but when i test it through fastly (test domain) i get an error in the browser

`{
  "code": "SRdzzwytzkWqwDpEriixF89YUQYKdhzt",
  "error": "There was an error processing your request."
}` 
and then when i check via wsk activation get i get:

'
            "error": "Initialization has failed due to: Error: Cannot find module 'request-promise-native'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:507:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.<anonymous> (/nodejsAction/XXcFnIne/static.js:13:17)\n    at Module._compile (internal/modules/cjs/loader.js:689:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)\n    at Module.load (internal/modules/cjs/loader.js:599:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"`

which is the initial error. 
From wsk activation list it looks like only hlx--static:0.0.7 was called

**Comment by wielmic** [comment] 2019-05-14 21:03
I tried it from ubuntu and it works. So the problem on windows is with bundler. The final package has modules but they are incomplete. Only folder from modules are collected and shipped.
For example:
windows content of the library from error:
- request-promise-native
      -lib
unix content:
- request-promise-native
      - lib
      - package.json
      - README.md
      - LICENSE
      - error.js
      - .npmignore
so there is package.json missing.

**Comment by tripodsan** [comment] 2019-05-14 23:46
most probably a path separator problem:
https://github.com/adobe/helix-cli/blob/ca4ec4e13c6bdcdea40f5bdf644b24aef1b09ee1/src/parcel/ExternalsCollector.js#L16

**Comment by wielmic** [comment] 2019-05-15 14:24
I will check this, thanks. It might take couple days because for the next few days i need to work on different things. I will update the ticket as soon as i find some time.

**Comment by wielmic** [comment] 2019-05-21 11:21
Should external collector return also content of modules? (Paths to files and subfolders)
It looks good, the output from ExternalCollector is a list of entriels like 
`
'request-promise-core':
   'C:\\Users\\wieli\\AppData\\Roaming\\npm\\node_modules\\@adobe\\helix-cli\\node_modules\\request-promise-core',
  'request-promise-native':
   'C:\\Users\\wieli\\AppData\\Roaming\\npm\\node_modules\\@adobe\\helix-cli\\node_modules\\request-promise-native',
`
Can this issue be in Package.cmd.js?

**Closed** 2019-05-27 09:06 UTC
Labels: bug
