### ISSUE TITLE
publish throws (non-fatal) errors

### ISSUE THREAD

**Issue by rofe** [adobe/helix-cli#498] opened 2019-02-04 18:58 UTC
**Description**
When pushing a project to Fastly using `hlx publish`, the following error occurs 3x:
```
error: Unknown error when deleting key <strain_name> from dictionary 1f4iuEU7hu0e5ASKfQYNTc404 - {"msg":"Record not found","detail":"Couldn't find DictionaryItem '{ deleted => 0000-00-00 00:00:00, dictionary_id => 1f4iuEU7hu0e5ASKfQYNTc, item_key => default, service => 0zWbuvDYjdlCTD1tGGUD2F }'"}
```
The site works regardless.

**Expected behavior**
No errors are visible in console output

**Version:**
0.13.3-pre1

**Comment by tripodsan** [comment] 2019-02-05 17:14
duplicate of #416

**Closed by tripodsan** 2019-02-05 17:14 UTC
Labels: bug
